responses = {
    "hola": "Hola, ¿cómo estás?",
    "que puedes hacer": "Puedo ayudarte con información y responder preguntas.",
    "que es un sustantivo": "Un sustantivo es una palabra que se utiliza para nombrar personas, animales, cosas, lugares o ideas. Por ejemplo, 'niño', 'perro', 'mesa' y 'amor' son sustantivos.",
    "dame un ejemplo de un verbo": "Un verbo es una palabra que describe una acción, un estado o un proceso. Por ejemplo, 'correr', 'estar' y 'crecer' son verbos.",
    "como se forma el plural de los sustantivos": "La mayoría de los sustantivos forman su plural añadiendo una 's' al final. Por ejemplo, 'gato' se convierte en 'gatos'. Sin embargo, hay excepciones como 'luz' que se convierte en 'luces' y 'pez' que se convierte en 'peces'.",
    "que es un adjetivo": "Un adjetivo es una palabra que describe o califica a un sustantivo. Por ejemplo, en la frase 'el perro grande', 'grande' es un adjetivo que describe al sustantivo 'perro'.",
    "que es una oracion simple": "Una oración simple es una oración que contiene un sujeto y un predicado y expresa una idea completa. Por ejemplo: 'El sol brilla'.",
    "que es una metafora": "Una metáfora es una figura retórica que compara dos cosas diferentes sin usar 'como' o 'parece'. Por ejemplo, 'Sus ojos son estrellas' compara los ojos con estrellas.",
    "que es una fabula": "Una fábula es una historia corta que generalmente tiene animales como personajes y enseña una lección o moraleja. Por ejemplo, 'La liebre y la tortuga'.",
    "dame un ejemplo de una figura literaria": "Una figura literaria es una herramienta que los escritores usan para embellecer su lenguaje. Por ejemplo, la aliteración es la repetición del sonido inicial en varias palabras: 'Tres tristes tigres tragan trigo en un trigal'.",
    "que es una silaba": "Una sílaba es una unidad de pronunciación que tiene al menos una vocal y puede tener consonantes. Por ejemplo, la palabra 'casa' tiene dos sílabas: 'ca' y 'sa'.",
    "que es un sinonimo": "Un sinónimo es una palabra que tiene un significado similar o igual a otra palabra. Por ejemplo, 'feliz' y 'contento' son sinónimos.",
    "que es un antonimo": "Un antónimo es una palabra que tiene un significado opuesto a otra palabra. Por ejemplo, 'alto' y 'bajo' son antónimos.",
    "que es un pronombre": "Un pronombre es una palabra que reemplaza a un sustantivo en una oración. Por ejemplo, 'él', 'ella', 'nosotros' y 'ustedes' son pronombres.",
    "dame un ejemplo de una oracion interrogativa": "Una oración interrogativa es una oración que hace una pregunta. Por ejemplo: '¿Cómo te llamas?'.",
    "que es una oracion exclamativa": "Una oración exclamativa es una oración que expresa una emoción fuerte y termina con un signo de exclamación. Por ejemplo: '¡Qué bonito es el día!'.",
    "que es una preposicion": "Una preposición es una palabra que muestra la relación entre un sustantivo o pronombre y otras palabras en una oración. Por ejemplo, 'en', 'sobre', 'bajo' y 'entre' son preposiciones.",
    "que es un articulo": "Un artículo es una palabra que se utiliza para indicar el género y el número de un sustantivo. Hay artículos definidos como 'el' y 'la', e indefinidos como 'un' y 'una'.",
    "como se conjuga el verbo ser en presente": "El verbo 'ser' se conjuga en presente de la siguiente manera: yo soy, tú eres, él/ella es, nosotros somos, vosotros sois, ellos/ellas son.",
    "que es un texto narrativo": "Un texto narrativo es un texto que cuenta una historia o relata hechos. Puede incluir cuentos, novelas y fábulas.",
    "que es un texto descriptivo": "Un texto descriptivo es un texto que describe las características de personas, lugares, objetos o situaciones. Su objetivo es que el lector pueda imaginar lo descrito.",
    "que es un texto expositivo": "Un texto expositivo es un texto que explica información sobre un tema específico. Su objetivo es informar y aclarar conceptos.",
    "que es un texto argumentativo": "Un texto argumentativo es un texto que presenta argumentos para defender una opinión o idea. Su objetivo es convencer al lector.",
    "que es una parabola": "Una parábola es una historia breve que ilustra una lección moral o espiritual. A menudo se encuentran en textos religiosos.",
    "que es una analogia": "Una analogía es una comparación entre dos cosas que son similares en algunos aspectos. Por ejemplo, 'El sol es a la luz como la luna es a la noche'.",
    "que es una hiperbole": "Una hipérbole es una figura retórica que consiste en exagerar una idea o situación para enfatizarla. Por ejemplo, 'Tengo tanta hambre que podría comerme un caballo'.",
    "que es una personificacion": "Una personificación es una figura literaria que consiste en atribuir cualidades humanas a objetos inanimados o animales. Por ejemplo, 'El viento susurraba entre los árboles'.",
    "que es una aliteracion": "Una aliteración es la repetición del sonido inicial en varias palabras de una misma frase o verso. Por ejemplo: 'Tres tristes tigres tragan trigo en un trigal'.",
    "que es una onomatopeya": "Una onomatopeya es una palabra que imita el sonido de la cosa que describe. Por ejemplo, 'tic-tac' imita el sonido de un reloj.",
    "que es un acronimo": "Un acrónimo es una palabra formada por las iniciales de varias palabras. Por ejemplo, 'NASA' es un acrónimo de 'National Aeronautics and Space Administration'.",
    "que es un haiku": "Un haiku es un tipo de poema japonés que tiene tres líneas. La primera línea tiene cinco sílabas, la segunda línea tiene siete sílabas y la tercera línea tiene cinco sílabas.",
    "que es un sinonimo": "Un sinónimo es una palabra que tiene un significado similar o igual a otra palabra. Por ejemplo, 'feliz' y 'contento' son sinónimos.",
    "que es un antonimo": "Un antónimo es una palabra que tiene un significado opuesto a otra palabra. Por ejemplo, 'alto' y 'bajo' son antónimos.",
    "que es un homonimo": "Un homónimo es una palabra que suena igual que otra pero tiene un significado diferente. Por ejemplo, 'banco' puede referirse a una institución financiera o a un asiento.",
    "que es una oracion subordinada": "Una oración subordinada es una oración que depende de otra principal para tener sentido completo. Por ejemplo: 'Cuando llegué, ellos ya se habían ido'.",
    "que es una oracion coordinada": "Una oración coordinada es una oración que se une a otra mediante conjunciones como 'y', 'o', 'pero'. Por ejemplo: 'Quiero ir al cine y después cenar'.",
    "que es el sujeto de una oracion": "El sujeto de una oración es la persona, animal o cosa de la que se habla en la oración. Por ejemplo, en 'El perro ladra', 'El perro' es el sujeto.",
    "que es el predicado de una oracion": "El predicado de una oración es lo que se dice del sujeto. Contiene el verbo y sus complementos. Por ejemplo, en 'El perro ladra', 'ladra' es el predicado.",
    "que es un complemento directo": "Un complemento directo es la parte de la oración que recibe directamente la acción del verbo. Por ejemplo, en 'Leo un libro', 'un libro' es el complemento directo.",
    "que es un complemento indirecto": "Un complemento indirecto es la parte de la oración que recibe el beneficio o el daño de la acción del verbo. Por ejemplo, en 'Doy un regalo a María', 'a María' es el complemento indirecto.",
    "que es una oracion en voz pasiva": "Una oración en voz pasiva es una oración donde el sujeto recibe la acción del verbo. Por ejemplo: 'El libro fue leído por Juan'.",
    "que es una oracion en voz activa": "Una oración en voz activa es una oración donde el sujeto realiza la acción del verbo. Por ejemplo: 'Juan leyó el libro'.",
    "que es una elipsis": "Una elipsis es una figura literaria que consiste en omitir una o varias palabras que se sobreentienden por el contexto. Por ejemplo: 'Yo llevaba flores y ellos, un libro' (se omite 'llevaban').",
    "que es una anafora": "Una anáfora es una figura literaria que consiste en repetir una o varias palabras al principio de dos o más versos o oraciones. Por ejemplo: 'Corre, corre, que te atrapo'.",
    "que es un epiteto": "Un epíteto es un adjetivo que destaca una cualidad del sustantivo y que generalmente es innecesaria. Por ejemplo: 'La blanca nieve'.",
    "que es una paradoja": "Una paradoja es una figura literaria que consiste en una contradicción aparente que, al analizarse, revela una verdad. Por ejemplo: 'Menos es más'.",
    "que es un oximoron": "Un oxímoron es una figura literaria que combina dos términos contradictorios en una sola expresión. Por ejemplo: 'Silencio ensordecedor'.",
    "que es una oracion compuesta subordinada": "Una oración compuesta subordinada es una oración que depende de otra principal para tener sentido completo. Por ejemplo: 'No salí porque llovía'.",
    "que es una oracion compuesta coordinada": "Una oración compuesta coordinada es una oración que se une a otra mediante conjunciones como 'y', 'o', 'pero'. Por ejemplo: 'Quiero ir al cine y después cenar'.",
"muchas gracias": "De nada, si necesitas algo estoy a tus ordenes'.",
}

def get_response(user_input):
    return responses.get(user_input.lower(), "Lo siento, no entiendo esa pregunta. ¿Puedes intentar con otra?")
